{
  'extends': ['airbnb', plugin:prettier/recommended],
  'rules':
    {
      'linebreak-style': 0,
      'react/no-array-index-key': 0,
      'react/forbid-prop-types': [2, { 'forbid': ['any'] }],
      'jsx-a11y/no-static-element-interactions': 0,
      'no-undef': 0,
      'quotes': [0, 'single', 'avoid-escape'],
      'prettier/prettier':
        [
          'error',
          {
            'singleQuote': true,
            'trailingComma': 'es5',
            'endOfLine': 'lf',
            'printWidth': 100,
            'tabWidth: 2',
          },
        ],
    },
  'parser': 'babel-eslint',
  'globals': { 'window': true, 'document': true },
}
